### PR TITLE
fix gradle version in sub-projects

### PR DESCRIPTION
**Pull request by joc-mer**
Gradle version is now aligned in sub-projects

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@joc-mer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-centralized-configuration&pullRequestId=9)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-centralized-configuration&pullRequestId=9) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@joc-mer Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-centralized-configuration&pullRequestId=9)!

**Comment by gregturn** [comment]
Thanks. Can you rebase?

**Comment by Buzzardo** [comment]
There's a newer version, and a more recent PR upgrades to that newer version, so we can close this one.

**Pull request closed without merging**
